version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: momento-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - nginx_logs:/var/log/nginx
    depends_on:
      - momento-server
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    restart: unless-stopped
    networks:
      - momento-network

  certbot:
    image: certbot/certbot
    container_name: momento-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: momento-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-momento_db}
      MYSQL_USER: ${MYSQL_USER:-momento_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - momento-network

  momento-server:
    build: .
    container_name: momento-server
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: https://dev.caffeineoverdose.shop/login/oauth2/code/kakao
      AUTHORIZED_REDIRECT_URIS: https://dev.caffeineoverdose.shop
      ALLOWED_ORIGINS: https://dev.caffeineoverdose.shop
      COOKIE_DOMAIN: .caffeineoverdose.shop
      SWAGGER_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - app_logs:/var/log/momento
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - momento-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data:
  app_logs:
  nginx_logs:

networks:
  momento-network:
    driver: bridge