spring:
  # 로컬 개발용 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/momento_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: HikariCP-Local

  # JPA 설정 (로컬 개발용)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

  # OAuth2 설정 (로컬 개발용)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # Redis 설정 (로컬 개발용)
  data:
    redis:
      host: localhost
      port: 6379
      password: # 로컬 Redis는 비밀번호 없음
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# 앱 설정 (로컬 개발용)
app:
  oauth2:
    authorized-redirect-uris: http://localhost:3000,https://momento-neon.vercel.app,https://dev.caffeineoverdose.shop
  cors:
    allowed-origins: http://localhost:3000,https://localhost:3000,http://127.0.0.1:3000,https://momento-neon.vercel.app,https://dev.caffeineoverdose.shop
  cookie:
    refresh-token:
      name: refreshToken
      max-age: 604800  # 7일
      secure: false  # HTTP에서는 false
      http-only: true
      same-site: lax

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini
  max-tokens: 300
  temperature: 0.8

# 서버 설정 (로컬용)
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

# 로깅 설정 (로컬 개발용 - 상세 로깅)
logging:
  level:
    # 프로젝트 전체 로깅
    com.challkathon.momento: DEBUG
    
    # 인증 관련 상세 로깅
    com.challkathon.momento.auth: TRACE
    com.challkathon.momento.auth.filter: TRACE
    com.challkathon.momento.auth.service: DEBUG
    com.challkathon.momento.auth.handler: DEBUG
    
    # Spring Security 상세 로깅
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.web: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    
    # JWT 처리 로깅
    io.jsonwebtoken: DEBUG
    
    # CORS 관련 로깅
    org.springframework.web.cors: DEBUG
    
    # MySQL/JPA 로깅
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    
    # Root 레벨
    root: INFO

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Swagger 설정 (로컬용 - 모든 기능 활성화)
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs:
    enabled: true

# 액추에이터 설정 (로컬용 - 개발 편의를 위해 더 많은 엔드포인트 노출)
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,beans,metrics
  endpoint:
    health:
      show-details: always
    env:
      show-values: always


# ⚠️ 주의: 개발 환경 전용 JWT 설정
# 운영 환경에서는 절대 사용하지 마세요!
# 긴 만료 시간은 개발 편의성을 위한 것입니다.
jwt:
  # 로컬 개발 환경 - 토큰 재발급 불편 최소화
  access-token-expiration: 31536000000  # 365일 (1년) - 실질적으로 무한
  refresh-token-expiration: 63072000000 # 730일 (2년) - 실질적으로 무한
  # 참고: 1시간 = 3,600,000ms, 1일 = 86,400,000ms, 1년 = 31,536,000,000ms